trigger: 
  - main

variables:
  System.Debug: true

jobs:
  - job: generateInput
    steps:
      - task: PowerShell@2
        name: GenerateMatrix
        inputs:
          targetType: 'inline'
          script: |
            $subscriptions = Import-Csv "$(System.DefaultWorkingDirectory)/.azdo/subscriptionIds.csv"
            $matrixItems = $($subscriptions | ForEach-Object { "'$($_.SubscriptionName)': { 'subscriptionId': '$($_.SubscriptionId)', 'tenantId': '$($_.TenantId)', 'serviceConnectionName', '$($_.ServiceConnectionName)' }," })
            $matrix = "{ " + "$matrixItems" + " }"
            Write-Host "##vso[task.setvariable variable=matrix;isOutput=true]$matrix"
  - job: runTerraform
    dependsOn: generateInput
    strategy:
      matrix: $[ dependencies.generateInput.outputs['GenerateMatrix.matrix'] ]
      maxParallel: 4
    steps:
      - task: TerraformInstaller@1
        displayName: install terraform
        inputs:
          terraformVersion: latest
      - task: TerraformTaskV4@4
        displayName: Initialize Terraform
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: '$(serviceConnectionName)'
          backendAzureRmResourceGroupName: 'rg-terraform'
          backendAzureRmStorageAccountName: 'saterraformrjb'
          backendAzureRmContainerName: 'azdo-yaml-loop-terraform'
          backendAzureRmKey: 'state.tfstate'
          commandOptions: '-backend-config="tenant_id=$(tenantId)"'
      - task: TerraformTaskV4@4
        displayName: 'terraform plan'
        inputs:
          provider: 'azurerm'
          command: plan
          workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
          commandOptions: '-var="subscription_id=$(subscriptionId)" -out=main.tfplan'
          environmentServiceNameAzureRM:  '$(serviceConnectionName)'
      - task: TerraformTaskV4@4
        displayName: 'terraform apply'
        inputs:
          provider: 'azurerm'
          command: apply
          workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
          commandOptions: 'main.tfplan'
          environmentServiceNameAzureRM:  '$(serviceConnectionName)'
