trigger: 
  - main

variables:
  System.Debug: true

jobs:
  - job: generateInput
    steps:
      - pwsh: |
          tree /F $(System.DefaultWorkingDirectory)
      - task: PowerShell@2
        name: GenerateMatrix
        inputs:
          targetType: 'inline'
          script: |
            $subscriptions = Import-Csv $(System.DefaultWorkingDirectory)/.azdo/subscriptionIds.csv
            $matrixItems = $($subscriptionIds | ForEach-Object { "'$($_.SubscriptionName)': { 'subscriptionId': '$($_.SubscriptionId)' }" })
            $matrix = "{ " + "$matrixItems" + " }"
            Write-Host "##vso[task.setvariable variable=matrix;isOutput=true]$matrix"
  - job: runTerraform
    dependsOn: generateInput
    strategy:
      matrix: $[ dependencies.generateInput.outputs['GenerateMatrix.matrix'] ]
    steps:
      - pwsh: |
          Get-ChildItem Env: